--- Business Requirement ---

select * from DELIVERIES;
-- Find the top 5 drivers who completed the highest number of deliveries. --
SELECT driver_id,
       COUNT(*) AS completed_deliveries
FROM deliveries
WHERE delivery_status = 'Completed'
GROUP BY driver_id
ORDER BY completed_deliveries DESC
FETCH FIRST 5 ROWS ONLY;


-- Find the top 5 fastest drivers based on their average delivery time for completed deliveries.--
SELECT driver_id,
       AVG(delivery_time_minutes) AS avg_time
FROM deliveries
WHERE delivery_status = 'Completed'
GROUP BY driver_id
ORDER BY avg_time ASC
FETCH FIRST 5 ROWS ONLY;


-- Find the top 5 drivers with the highest average customer review rating. --
SELECT e.driver_id,
       AVG(r.rating) AS avg_rating
FROM delivery_reviews r
JOIN deliveries e
    ON r.delivery_id = e.delivery_id
WHERE e.delivery_status = 'Completed'
GROUP BY e.driver_id
ORDER BY avg_rating DESC
FETCH FIRST 5 ROWS ONLY;


-- Find the top 5 drivers generating the highest total company commission from completed deliveries. --
select e.driver_id, sum(p.company_commission) as Highest_total_company_commission
from delivery_payments p 
join deliveries e on p.delivery_id = e.delivery_id
where e.delivery_status = 'Completed'
group by e.driver_id
order by  Highest_total_company_commission DESC
FETCH FIRST 5 ROWS ONLY;


-- Find the top 5 drivers with the highest number of cancelled deliveries. --
select driver_id, count(delivery_status) as Number_of_cancelled_Orders
from DELIVERIES
where delivery_status ='Cancelled'
group by DRIVER_ID
order by Number_of_cancelled_Orders DESC
FETCH FIRST 5 ROWS ONLY;

-- Find the pickup city with the highest number of completed deliveries. --
select pickup_city, MAX(delivery_status),COUNT(delivery_status) as Number_of_completed_deliveries
from deliveries 
where delivery_status = 'Completed'
group by PICKUP_CITY
order by Number_of_completed_deliveries DESC;


-- Find the average delivery time for each pickup city for completed deliveries. --
select pickup_city, avg(delivery_time_minutes) as avg_time
from deliveries 
where delivery_status = 'Completed'
group by PICKUP_CITY
order by avg_time ASC;


select * from delivery_payments;

-- Find the total delivery revenue generated by each pickup city from completed deliveries.--
select e.PICKUP_CITY, sum(p.delivery_charge) as Total_revenue
from DELIVERY_PAYMENTS p 
join deliveries e on p.delivery_id = e.DELIVERY_ID
where e.DELIVERY_STATUS = 'Completed'
group by e.PICKUP_CITY
order by Total_revenue DESC;


-- Find the top 5 pickup-to-delivery city routes with the highest number of completed deliveries. --
select pickup_city, delivery_city , count(delivery_status) as Number_of_completed
from deliveries 
where delivery_status = 'Completed'
group by pickup_city,DELIVERY_CITY
order by Number_of_completed DESC
FETCH FIRST 5 ROWS ONLY;


-- Find the average delivery distance for each driver from completed deliveries. --
select driver_id, AVG(distance_km) as AVG_Distance
from DELIVERIES
where DELIVERY_STATUS = 'Completed'
group by driver_id
order by AVG_Distance ASC;


-- Find the total amount paid to each driver for completed deliveries. --
select e.driver_id, sum(p.driver_payment) as Driver_Amount
from delivery_payments p 
join deliveries e
on p.delivery_id = e.delivery_id 
where e.delivery_status = 'Completed'
group by e.driver_id
order by Driver_Amount DESC;


-- Find the payment method generating the highest total delivery revenue from completed deliveries. --
select p.payment_method, sum(p.delivery_charge) as Total_revenue
from DELIVERY_PAYMENTS p 
join deliveries e on p.delivery_id =  e.DELIVERY_ID
where e.delivery_status ='Completed'
group by p.PAYMENT_METHOD
order by total_revenue desc;

-- Find the top 5 drivers with the highest average customer rating and show their number of completed deliveries.--
select e.DRIVER_ID, avg(r.rating) as AVR_Rating, count(r.delivery_id) as Count_of_Completed
from delivery_reviews r
join deliveries e 
on r.delivery_id = e.delivery_id 
where delivery_status = 'Completed' and  e.driver_id IS NOT NULL and r.rating is not NULL
group by e.DRIVER_ID
order by AVR_Rating DESC
FETCH FIRST 5 ROWS ONLY;


-- Find the top 5 drivers generating the highest total delivery revenue from completed deliveries. --
select e.driver_id, sum(p.delivery_charge) as Total_revenue
from delivery_payments p
join deliveries e 
on p.delivery_id = e.DELIVERY_ID
where e.delivery_status = 'Completed' and  e.driver_id IS NOT NULL
group by e.DRIVER_ID
order by Total_revenue DESC
FETCH FIRST 5 ROWS ONLY;


-- Find the top 5 drivers with the highest total distance covered through completed deliveries. --
select driver_id, sum(distance_KM) as Total_distance_coverd
from DELIVERIES
where delivery_status = 'Completed' and driver_id is not NULL and driver_id <> ('Unknow')
group by driver_id 
order by Total_distance_coverd DESC
FETCH FIRST 5 ROWS ONLY ;


-- Find the top 5 drivers with the highest cancellation rate.--
SELECT driver_id,
       COUNT(CASE
                 WHEN delivery_status = 'Cancelled'
                 THEN 1
             END) AS cancelled_deliveries,
       COUNT(*) AS total_deliveries,
       ROUND(
           COUNT(CASE
                     WHEN delivery_status = 'Cancelled'
                     THEN 1
                 END) / COUNT(*) * 100,
           2
       ) AS cancellation_rate
FROM deliveries
WHERE driver_id IS NOT NULL
GROUP BY driver_id
ORDER BY cancellation_rate DESC
FETCH FIRST 5 ROWS ONLY;



-- Find the top 5 drivers with the highest average payment per completed delivery. --
select e.driver_id, avg(p.driver_payment) as AVG_PAYEMNT 
from DELIVERY_PAYMENTS p
join deliveries e
on p.delivery_id = e.DELIVERY_ID
where e.delivery_status = 'Completed'
 and e.DRIVER_ID is not null
    and p.driver_payment IS not NULL
group by e.DRIVER_ID
order by AVG_PAYEMNT DESC
FETCH FIRST 5 ROWS ONLY;



-- Find the top 5 drivers with the highest average company commission per completed delivery. --
select e.driver_id, AVG(p.company_commission) as AVG_company_commission
from DELIVERY_PAYMENTS p
join deliveries e
on p.delivery_id = e.delivery_id 
where e.delivery_status = 'Completed'
and e.driver_id is not null 
and p.company_commission is not null
group by e.driver_id
order by AVG_company_commission DESC
FETCH FIRST 5 ROWS ONLY;



-- Find the top 5 drivers with the highest completion rate. --
select driver_id, count(
    case when delivery_status = 'Completed' THEN 1 END) as Completed_deliveries,
     count(*) as total_deliveries,
round(count(case when delivery_status = 'Completed' THEN 1 END) / count(*) * 100, 2) AS Completion_Rate
from deliveries 
WHERE driver_id IS NOT NULL
GROUP BY driver_id
ORDER BY Completion_Rate DESC
FETCH FIRST 5 ROWS ONLY;



-- Find the top 5 drivers with the highest average delivery time for completed deliveries. --
select driver_id, AVG(delivery_time_minutes) as avg_time
from DELIVERIES
where delivery_status = 'Completed' 
and driver_id is not null
and delivery_time_minutes is not null 
group by driver_id
order by avg_time DESC
FETCH FIRST 5 ROWS ONLY;



-- Find the top 5 pickup cities with the highest average delivery charge for completed deliveries.--
select e.pickup_city, avg(p.delivery_charge) as AVG_delivery_charge 
from DELIVERY_PAYMENTS p 
join deliveries e 
on p.delivery_id = e.delivery_id 
where e.delivery_status = 'Completed'
group by e.pickup_city 
order by AVG_delivery_charge desc
FETCH FIRST 5 ROWS ONLY;



-- Find the top 5 delivery routes with the highest total revenue from completed deliveries. --
select e.pickup_city, e.delivery_city, SUM(p.delivery_charge) as Total_Revenu 
from delivery_payments p 
join deliveries e 
on p.delivery_id = e.delivery_id 
where e.delivery_status = 'Completed'
group by e.pickup_city,e.delivery_city 
order by Total_Revenu DESC
FETCH FIRST 5 ROWS ONLY;



-- Find the top 5 drivers with the highest number of 5-star reviews. -- 
select e.driver_id,count(r.rating) as Rating 
from delivery_reviews r 
join deliveries e 
on r.delivery_id = e.delivery_id 
where r.rating = 5
AND e.driver_id IS NOT NULL
group by e.driver_id
order by rating desc
fetch first 5 rows only;


-- Find the top 5 drivers with the lowest average customer rating from completed deliveries. --
select e.driver_id,AVG(r.rating) as AVG_Rating 
from delivery_reviews r 
join deliveries e 
on r.delivery_id = e.delivery_id 
where e.delivery_status = 'Completed'
AND e.driver_id IS NOT NULL
group by e.driver_id
order by AVG_rating ASC
fetch first 5 rows only;


-- Find the top 5 drivers with the highest number of customer reviews from completed deliveries. --
SELECT e.driver_id,
       COUNT(*) AS total_reviews
FROM delivery_reviews r
JOIN deliveries e
    ON r.delivery_id = e.delivery_id
WHERE e.delivery_status = 'Completed'
  AND e.driver_id IS NOT NULL
GROUP BY e.driver_id
ORDER BY total_reviews DESC
FETCH FIRST 5 ROWS ONLY;



-- Find the percentage of completed deliveries that received a 5-star rating. --
SELECT
    COUNT(CASE WHEN r.rating = 5 THEN 1 END) AS five_star_reviews,
    COUNT(*) AS total_completed_reviews,
    ROUND(
        COUNT(CASE WHEN r.rating = 5 THEN 1 END)
        / COUNT(*) * 100,
        2
    ) AS five_star_percentage
FROM deliveries e
JOIN delivery_reviews r
    ON e.delivery_id = r.delivery_id
WHERE e.delivery_status = 'Completed';


-- Find the top 5 pickup cities with the highest number of cancelled deliveries. --
select pickup_city, count(delivery_status) as highest_number_of_cancelled_deliveries
from deliveries 
where delivery_status = 'Cancelled'
group by PICKUP_CITY
order by highest_number_of_cancelled_deliveries desc 
fetch first 5 rows only;



-- Find the top 5 delivery cities with the highest total revenue from completed deliveries.--
select e.delivery_city , sum(p.delivery_charge) as Total_Revenu 
from DELIVERY_PAYMENTS p
join deliveries e
on p.delivery_id = e.delivery_id 
where e.delivery_status = 'Completed'
group by e.delivery_city 
order by Total_Revenu desc 
FETCH FIRST 5 ROWS ONLY;


-- Find the top 5 routes with the longest average delivery distance among completed deliveries. --
select pickup_city, delivery_city, AVG(distance_km) as longest_average_delivery_distance
from deliveries 
where delivery_status = 'Completed' and distance_km is not null 
group by pickup_city, delivery_city 
order by longest_average_delivery_distance desc 
FETCH FIRST 5 ROWS ONLY;



-- Find the top 5 pickup cities with the highest average delivery time for completed deliveries. --
select pickup_city, avg(delivery_time_minutes) as highest_average_delivery_time
from deliveries 
where delivery_status = 'Completed' and delivery_time_minutes is not null 
group by PICKUP_CITY
order by highest_average_delivery_time desc 
FETCH FIRST 5 ROWS ONLY;


-- Rank each driver based on total revenue generated from completed deliveries. --
SELECT driver_id,
       total_revenue,
       RANK() OVER (ORDER BY total_revenue DESC) AS rank_id
FROM (
    SELECT e.driver_id,
           SUM(p.delivery_charge) AS total_revenue
    FROM delivery_payments p
    JOIN deliveries e
        ON p.delivery_id = e.delivery_id
    WHERE e.delivery_status = 'Completed'
      AND e.driver_id IS NOT NULL
      AND p.delivery_charge IS NOT NULL
    GROUP BY e.driver_id
)
ORDER BY rank_id;



-- Find the top 3 drivers in each city based on total completed-delivery revenue. --
SELECT driver_id,
       city,
       total_revenue,
       rank_id
FROM (
    SELECT driver_id,
           city,
           total_revenue,
           RANK() OVER (
               PARTITION BY city
               ORDER BY total_revenue DESC
           ) AS rank_id
    FROM (
        SELECT e.driver_id,
               d.city,
               SUM(p.driver_payment) AS total_revenue
        FROM delivery_payments p
        JOIN deliveries e
            ON p.delivery_id = e.delivery_id
        JOIN drivers d
            ON e.driver_id = d.driver_id
        WHERE e.delivery_status = 'Completed'
          AND e.driver_id IS NOT NULL
          AND p.driver_payment IS NOT NULL
        GROUP BY e.driver_id, d.city
    )
)
WHERE rank_id <= 3
ORDER BY city, rank_id;




-- Find the top 3 drivers in each city based on their completion rate. --
SELECT driver_id,
       city,
       Completion_rate,
       rank_id
FROM (SELECT driver_id,
           city,
           Completion_rate,
           RANK() OVER (
               PARTITION BY city
               ORDER BY Completion_rate DESC
           ) AS rank_id
    FROM (select d.driver_id, d.city, count(case when e.delivery_status = 'Completed' THEN 1 END) as completed_deliveries, count(*) as total_deliveries,
round(count(case when e.delivery_status = 'Completed' THEN 1 END) / count(*) * 100,2) as Completion_rate
from deliveries e
JOIN drivers d
    ON e.driver_id = d.driver_id
where e.driver_id IS NOT NULL
GROUP BY d.driver_id,d.city
    )
)
WHERE rank_id <= 3
ORDER BY city, rank_id;



-- Find the top 3 drivers in each city based on their total distance covered from completed deliveries. --
select driver_id, city, Total_Distance, Rank_id
from( select driver_id, city, Total_Distance, Rank() over(PARTITION BY city ORDER BY Total_Distance DESC) as Rank_id
from(select d.driver_id, d.city, sum(e.distance_km) as Total_Distance 
    from deliveries e
    join drivers d 
    on e.driver_id = d.driver_id 
    where e.delivery_status = 'Completed' and d.driver_id is not null
    and e.distance_km is not null
    group by d.driver_id, d.city 
)

)
WHERE rank_id <= 3
ORDER BY city, rank_id;



-- Find the top 3 drivers in each city based on their average customer rating from completed deliveries. --
SELECT driver_id,
       city,
       avg_rating,
       rank_id
FROM (
    SELECT driver_id,
           city,
           avg_rating,
           RANK() OVER (
               PARTITION BY city
               ORDER BY avg_rating DESC
           ) AS rank_id
    FROM (
        SELECT d.driver_id,
               d.city,
               AVG(r.rating) AS avg_rating
        FROM delivery_reviews r
        JOIN deliveries e
            ON r.delivery_id = e.delivery_id
        JOIN drivers d
            ON e.driver_id = d.driver_id
        WHERE e.delivery_status = 'Completed'
          AND r.rating IS NOT NULL
        GROUP BY d.driver_id, d.city
    )
)
WHERE rank_id <= 3
ORDER BY city, rank_id;

